---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Prepare host for an OpenShift Standalone Registry installation
  hosts: nodes
  become: yes
  tasks:
    - include_role:
        name: host-preparation

    - name: Configure a reencrypt route for docker-registry
      oc_route:
        name: docker-registry-dev
        namespace: "default"
        service_name: docker-registry
        tls_termination: "reencrypt"
        host: "trunk.registry.dev.rdoproject.org"
        cert_path: "/etc/letsencrypt/live/trunk.registry.dev.rdoproject.org/trunk.registry.dev.rdoproject.org-cert.pem"
        key_path: "/etc/letsencrypt/live/trunk.registry.dev.rdoproject.org/trunk.registry.dev.rdoproject.org-privkey.pem"
        cacert_path: "/etc/letsencrypt/live/trunk.registry.dev.rdoproject.org/trunk.registry.dev.rdoproject.org-chain.pem"
        dest_cacert_path: "/etc/origin/master/ca.crt"

    - name: create the rhosp12 project
      oc_project:
        state: present
        name: rhosp12
        display_name: Red Hat OSP12 images

    - name: create the dci-feeder serviceaccount
      oc_serviceaccount:
        name: osp-feeder
        namespace: default
      register: sa_out

    - debug:
        var: sa_out

    - name: associate rhosp12 to the osp-feeder serviceaccount
      oc_adm_policy_user:
        user: osp-feeder
        resource_kind: cluster-role
        resource_name: system:serviceaccount:rhosp12:rhosp12.service
        state: present
