---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

host_preparation_domain: registry.rdoproject.org
host_preparation_registry: trunk.registry.rdoproject.org
host_preparation_console: console.registry.rdoproject.org

host_preparation_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - docker
  - pyOpenSSL

# OpenStack (TripleO) clouds have a default MTU of 1450, we need to override
# the 1500 default
host_preparation_docker_mtu: 1400

# It is expected that the host has an additional cinder volume/disk for the
# storage of containers and images.
# host_preparation_docker_disk: "/dev/vdb"
